### ISSUE TITLE
Does the dataset of Show-o contain synthetic data?

### ISSUE THREAD

**Issue by nunbuzor** [showlab/Show-o#1]

**Comment by Sierkinhane** [comment]
Hi, there are no synthetic images but we use the ShareGPT4V to recaption these real images.

**Comment by Fa-ti-ma** [comment]
hey, thank for your great work! I have a question regarding the captioning model, which variant did you use, the 7B or 13B?

**Comment by Sierkinhane** [comment]
Hi, we used the 7B model.

**Comment by Fa-ti-ma** [comment]
@Sierkinhane Thank you for the prompt reply! I need more clarification, In the ShareGPT4v repo, they have two models, the first one is ShareCaptioner (the one used to generate the 1.2M captions) and the other is ShareGPT4v which has two variants (7B and 13B). So, which one did you utilize?

**Comment by Sierkinhane** [comment]
Hi, we used the ShareCaptioner.

**Comment by Fa-ti-ma** [comment]
@Sierkinhane Thank you! :)
