### ISSUE TITLE
Impact of Various Representations for Multimodal Understanding

### ISSUE THREAD

**Issue by Doctor-James** [showlab/Show-o#13]
Thank you for your outstanding work.
This paper follows the MAGVIT-v2 framework, utilizing a discrete tokenizer. However, the results from the ablation study and Table 1 indicate that continuous feature representation significantly outperforms discrete representation. Yet, the paper ultimately opts for discrete representation. What considerations led to this choice?

**Comment by Sierkinhane** [comment]
Hi, these results are for multimodal understanding, not generation. Besides, these continuous features are from CLIP-ViT, not VAE typically used in diffusion models.

The discrepancy between continuous and discrete features for understanding may originate from the various scales of pre-training data. CLIP was pre-trained on around 400M image-text pairs, which is significantly larger than that of ours (35M). When using the same scale of training data, as shown in exp4 and exp6 in Table 4, discrete tokens demonstrate comparable performance to the continuous ones from MAGVIT-v2. Besides, continuous features from CLIP-ViT are extracted from images in a resolution of 336x336, and discrete tokens are extracted from images of 256x256.

The core reason we adopt discrete tokens is that the unified model can be tasked with the same learning objective, predicting discrete tokens for both text and images.
