### ISSUE TITLE
The reason of continuous feature is better than discrete feature is before the codebook size is small? 

### ISSUE THREAD

**Issue by dongzhuoyao** [showlab/Show-o#19]
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/19f88b74-8e9d-45a1-922c-8454ae78ad86">

check: https://github.com/TencentARC/Open-MAGVIT2/

<img width="860" alt="image" src="https://github.com/user-attachments/assets/5c8ebb91-1dde-4fd0-9197-fca7ef5ea40a">

<img width="1311" alt="image" src="https://github.com/user-attachments/assets/4d4d1fe7-08e5-4681-ad39-d1726b3e296c">

**Comment by Sierkinhane** [comment]
Hi, increasing the codebook size and the number of tokens to represent an image may improve the performance. In the setting of using MAGVITv2, I think discrete tokens can achieve comparable performance to that of continuous representations.
