### ISSUE TITLE
multimodal input -> image output

### ISSUE THREAD

**Issue by Redtides0** [showlab/Show-o#28]
Great work! 

I have arranged the input tokens for mm2i according to the token arrangement method for Mixed-Modality Generation described in Figure 3 of the paper. The arrangement is as follows: 

[T2I] [SOI] [image token 0] … [image token 255] [EOI] [SOT] [text token 0] … [text token n] [EOT] [SOI] [mask token 0] … [mask token 255] [EOI]

with the model tasked to predict the mask tokens. However, the current results are not satisfactory. Could you please advise on any issues with this arrangement and how they might be corrected?

**Comment by Cominclip** [comment]
Hi, have you resolved this issue? Does Show-o support multi-image input?

**Comment by HuiSiqi** [comment]
I also met this problem. 
When I use  [T2I][SOT] [text token 0] … [text token n] [EOT] [SOI] [image token 0] … [image token 1024]  [EOI] [SOI] [mask token 0] … [mask token 1024] [EOI] . The show-o just outputs a white picture.
